# Generated by Django 3.1.14 on 2022-06-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20220316_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_moveout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='can_moveout',
            field=models.BooleanField(default=True),
        ),
    ]
