# Generated by Django 3.1.14 on 2022-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20220602_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='can_moveout',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='can_moveout',
        ),
    ]
